### ISSUE TITLE
环境配置问题

### ISSUE THREAD

**Issue by goodCarlosJames** [19801201/DOSLAM#1]
1.刚开始是build.sbt能Build Module,但是运行top.scala会报错
Error:scalac: Error: org.jetbrains.jps.incremental.scala.remote.ServerException
java.lang.reflect.InvocationTargetException

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)

	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)

	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)

	at scala.tools.nsc.plugins.Plugin$.instantiate(Plugin.scala:178)

	at scala.tools.nsc.plugins.Plugins.loadRoughPluginsList(Plugins.scala:56)

	at scala.tools.nsc.plugins.Plugins.loadRoughPluginsList$(Plugins.scala:36)

	at scala.tools.nsc.Global.loadRoughPluginsList(Global.scala:45)

	at scala.tools.nsc.Global.roughPluginsList$lzycompute(Global.scala:45)

	at scala.tools.nsc.Global.roughPluginsList(Global.scala:45)

	at scala.tools.nsc.plugins.Plugins.loadPlugins(Plugins.scala:140)

	at scala.tools.nsc.plugins.Plugins.loadPlugins$(Plugins.scala:115)

	at scala.tools.nsc.Global.loadPlugins(Global.scala:45)

	at scala.tools.nsc.Global.plugins$lzycompute(Global.scala:45)

	at scala.tools.nsc.Global.plugins(Global.scala:45)

	at scala.tools.nsc.plugins.Plugins.computePluginPhases(Plugins.scala:167)

	at scala.tools.nsc.plugins.Plugins.computePluginPhases$(Plugins.scala:166)

	at scala.tools.nsc.Global.computePluginPhases(Global.scala:45)

	at scala.tools.nsc.Global.computePhaseDescriptors(Global.scala:750)

	at xsbt.ZincCompiler.phaseDescriptors$lzycompute(CallbackGlobal.scala:125)

	at xsbt.ZincCompiler.phaseDescriptors(CallbackGlobal.scala:119)

	at scala.tools.nsc.Global$Run.<init>(Global.scala:1285)

	at xsbt.ZincCompiler$ZincRun.<init>(CallbackGlobal.scala:63)

	at xsbt.CachedCompiler0.run(CompilerInterface.scala:128)

	at xsbt.CachedCompiler0.run(CompilerInterface.scala:105)

	at xsbt.CompilerInterface.run(CompilerInterface.scala:31)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.lang.reflect.Method.invoke(Method.java:498)

	at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:237)

	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:111)

	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:90)

	at org.jetbrains.jps.incremental.scala.local.IdeaIncrementalCompiler.compile(IdeaIncrementalCompiler.scala:40)

	at org.jetbrains.jps.incremental.scala.local.LocalServer.compile(LocalServer.scala:35)

	at org.jetbrains.jps.incremental.scala.remote.Main$.make(Main.scala:83)

	at org.jetbrains.jps.incremental.scala.remote.Main$.nailMain(Main.scala:26)

	at org.jetbrains.jps.incremental.scala.remote.Main.nailMain(Main.scala)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.lang.reflect.Method.invoke(Method.java:498)

	at com.martiansoftware.nailgun.NGSession.run(NGSession.java:319)

Caused by: java.lang.NoClassDefFoundError: scala/tools/nsc/transform/Transform$class

	at spinal.idslplugin.components.MainTransformer.<init>(MainTransformer.scala:9)

	at spinal.idslplugin.IdslPlugin.<init>(IdslPlugin.scala:11)

	... 43 more

Caused by: java.lang.ClassNotFoundException: scala.tools.nsc.transform.Transform$class

	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)

	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)

	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

	... 45 more
![1](https://github.com/user-attachments/assets/1f0cc0c3-8a85-460f-ab17-a947bc4b04f7)

把配置libraryDependencies ++= Seq(
  "com.github.spinalhdl" % "spinalhdl-core_2.11" % "1.9.3",
  "com.github.spinalhdl" % "spinalhdl-lib_2.11" % "1.9.3",
  compilerPlugin("com.github.spinalhdl" % "spinalhdl-idsl-plugin_2.11" % "1.9.3"),
)改成了libraryDependencies += "com.github.spinalhdl" %% "spinalhdl-core" % "1.9.3"
libraryDependencies += "com.github.spinalhdl" %% "spinalhdl-lib" % "1.9.3"
libraryDependencies += "com.github.spinalhdl" %% "spinalhdl-idsl-plugin" % "1.9.3" 
2.改后运行top报错如图2，
![2](https://github.com/user-attachments/assets/13b00add-e5e3-4ddd-b99a-1ea674090fa9)

将axis_desc(config) setAsReg()改为axis_desc(config).setAsReg();width bits改为width.bits,修改BRIEF.scala中的filename为   val filename: String = "C:\\Users\\10412\\Desktop\\test2\\src\\main\\data\\Coordinate.dat"自己路径，再次运行报错
HIERARCHY VIOLATION, (toplevel/[ORB_Compute]/??? : out Bits[32 bits]) can't be used in null at
    Top.<init>(top.scala:191)
    Top$.$anonfun$new$8(top.scala:259)
    spinal.sim.JvmThread.run(SimManager.scala:51)

********************************************************************************
********************************************************************************

HIERARCHY VIOLATION, (toplevel/[ORB_Compute]/??? : out Bits[32 bits]) can't be used in null at
    Top.<init>(top.scala:191)
    Top$.$anonfun$new$8(top.scala:259)
    spinal.sim.JvmThread.run(SimManager.scala:51)

********************************************************************************
********************************************************************************

HIERARCHY VIOLATION, (toplevel/[ORB_Compute]/??? : in Bool) can't be used in null at
    Top.<init>(top.scala:255)
    Top$.$anonfun$new$8(top.scala:259)
    spinal.sim.JvmThread.run(SimManager.scala:51)

********************************************************************************
********************************************************************************

Design's errors are listed above.
SpinalHDL compiler exit stack : 

	at spinal.core.SpinalExit$.apply(Misc.scala:441)
	at spinal.core.SpinalError$.apply(Misc.scala:496)
	at spinal.core.internals.PhaseContext.checkPendingErrors(Phase.scala:177)
	at spinal.core.internals.PhaseContext.doPhase(Phase.scala:193)
	at spinal.core.internals.SpinalVerilogBoot$.$anonfun$singleShot$12(Phase.scala:2976)
	at spinal.core.internals.SpinalVerilogBoot$.$anonfun$singleShot$12$adapted(Phase.scala:2974)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:619)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:617)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:935)
	at spinal.core.internals.SpinalVerilogBoot$.$anonfun$singleShot$7(Phase.scala:2974)
	at spinal.core.ScopeProperty$.sandbox(ScopeProperty.scala:71)
	at spinal.core.internals.SpinalVerilogBoot$.singleShot(Phase.scala:2910)
	at spinal.core.internals.SpinalVerilogBoot$.apply(Phase.scala:2905)
	at spinal.core.Spinal$.apply(Spinal.scala:412)
	at spinal.core.SpinalConfig.generate(Spinal.scala:176)
	at spinal.core.SpinalVerilog$.apply(Spinal.scala:431)
	at Top$.delayedEndpoint$Top$1(top.scala:259)
	at Top$delayedInit$body.apply(top.scala:258)
	at scala.Function0.apply$mcV$sp(Function0.scala:42)
	at scala.Function0.apply$mcV$sp$(Function0.scala:42)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1(App.scala:98)
	at scala.App.$anonfun$main$1$adapted(App.scala:98)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:619)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:617)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:935)
	at scala.App.main(App.scala:98)
	at scala.App.main$(App.scala:96)
	at Top$.main(top.scala:258)
	at Top.main(top.scala)

![3](https://github.com/user-attachments/assets/3513d527-9b06-4fdd-9360-92da50371fdb)

**Comment by hyfgouzi** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
